matrix:
  - JOB="./gradlew build"
script: "$JOB"

notifications:
  email:
    recipients:
        j.inglese@studenti.unisannio.it 
on_success: always
on_failure: always

notifications:
  slack: progettosw:FVxpq6vcaKjqIVqD485ZN0YJ
