{
  "email": "j.inglese@studenti.unisannio.it",
  "on_success": "always",
  "on_failure": "always",
  "language": "ruby",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "script": [
    "$JOB"
  ],
  "jobs": [
    "JOB=\"./gradlew build\""
  ]
}
