language : java

script : cd HelloProva && ./gradlew build

notifications:
  email:
    recipients:
       - j.inglese@studenti.unisannio.it 
    on_success: always
    on_failure: always
  
  slack: progettosw:FVxpq6vcaKjqIVqD485ZN0YJ
