matrix:
  - JOB="./gradlew build"

script: "$JOB"

cache:
directories:
~/.gradle/caches/
~/.gradle/wrapper/

notifications:
email:
       - j.inglese@studenti.unisannio.it      
on_success: always
on_failure: always
